apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: project
  name: project-material-ingress 
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: project-frontend-svc
            port: 
              number: 2345
      - path: /api
        backend:
          service:
            name: project-backend-svc
            port: 
              number: 2345