name: Delete environment from GKE

on:
  repository_dispatch:
    types: [deleted]

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
   build-publish-deploy:
     name: Delete environment
     runs-on: ubuntu-latest

     steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: google-github-actions/setup-gcloud@master
          with:
            service_account_key: ${{ secrets.GKE_SA_KEY }}
            project_id: ${{ secrets.GKE_PROJECT }}
            export_default_credentials: true

        - run: gcloud --quiet auth configure-docker

        - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
        - name: Delete
          run: |-
            kubectl delete all --all -n ${GITHUB_REF#refs/heads/}